# Translations template for python-fedora.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the python-fedora
# project.
# 
# Translators:
# Sulyok Péter <peti@fedoraproject.org>, 2009.
# Zoltan Hoppár <hopparz@gmail.com>, 2011, 2012.
msgid ""
msgstr ""
"Project-Id-Version: python-fedora\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2012-02-13 14:44-0800\n"
"PO-Revision-Date: 2012-02-15 12:04+0000\n"
"Last-Translator: Zoltan Hoppár <hopparz@gmail.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: fedora/iterutils.py:36
msgid "fedora.iterutils is deprecated.  Use kitchen.iterutils instead"
msgstr "fedora.iterutils elavult.  Alkalmazza a kitchen.iterutils helyette"

#: fedora/iterutils.py:54
msgid ""
"fedora.iterutils.isiterable is deprecated, use kitchen.iterutils.isiterable "
"instead"
msgstr "fedora.iterutils.isiterable elavult, alkalmazza a kitchen.iterutils.isiterable helyette"

#: fedora/release.py:9
msgid "Python modules for interacting with Fedora Services"
msgstr "Python modulok a Fedora Szolgáltatások együttműködéséhez"

#: fedora/release.py:10
msgid ""
"\n"
"The Fedora Project runs many different services.  These services help us to\n"
"package software, develop new programs, and generally put together the distro.\n"
"This package contains software that helps us do that.\n"
msgstr "\nA Fedora Project több különféle szolgáltatást működtet.  Ezek a szolgáltatások segítenek számunkra\nhogy szoftvereket csomagoljunk, új programokat fejlesszünk, és egyáltalán új kiadást rakjunk össze.\nEz a csomag ezekhez a feladatokhoz nyújt segítséget.\n"

#: fedora/textutils.py:33
msgid "fedora.textutils is deprecated.  Use kitchen.text.converters instead"
msgstr "fedora.textutils elavult.  Alkalmazza a kitchen.text.converters helyette"

#: fedora/accounts/fas2.py:8
msgid ""
"fedora.accounts.fas2 has moved to fedora.client.fas2.  This location will "
"disappear in 0.4"
msgstr "fedora.accounts.fas2 elköltözött fedora.client.fas2 helyre.  E hely el fog tűnni 0.4-ben"

#: fedora/client/__init__.py:89
msgid ""
"DictContainer is deprecated.  Use the Bunch class from python-bunch instead."
msgstr "A DictContainer elavult.  Alkalmazza a Bunch osztályt python-bunch helyett."

#: fedora/client/baseclient.py:94 fedora/client/baseclient.py:215
#: fedora/client/baseclient.py:234 fedora/client/baseclient.py:246
msgid "session_cookie is deprecated, use session_id instead"
msgstr "session_cookie elavult, használjon session_id-t"

#: fedora/client/baseclient.py:112
#, python-format
msgid "Unable to load session from %(file)s"
msgstr "Nem sikerült %(file)s fájlból munkafolyamatot betölteni"

#: fedora/client/baseclient.py:129
#, python-format
msgid "Unable to create %(dir)s: %(error)s"
msgstr "Nem sikerült elkészíteni %(dir)s mappát: %(error)s"

#: fedora/client/baseclient.py:141
#, python-format
msgid "Unable to write to session file %(session)s: %(error)s"
msgstr "Nem sikerült %(session)s munkafolyamat fájlba írni: %(error)s"

#: fedora/client/baseclient.py:164
#, python-format
msgid "No session cached for \"%s\""
msgstr "Nincs betárazva munkafolyamat „%s” azonosítóhoz"

#: fedora/client/baseclient.py:301
#, python-format
msgid "send_request() got an unexpected keyword argument \"%(arg)s\""
msgstr "a send_request() egy váratlan kulcsszó paramétert kapott \"%(arg)s\""

#: fedora/client/baseclient.py:305
msgid "send_request() got an unexpected keyword argument \"input\""
msgstr "send_request() váratlan „input” kulcsszó argumentumot kapott"

#: fedora/client/baseclient.py:309
msgid "send_request() got an unexpected keyword argument"
msgstr "send_request() váratlan kulcsszó argumentumot kapott"

#: fedora/client/baseclient.py:313
msgid ""
"send_request(input) is deprecated.  Use send_request(req_params) instead"
msgstr "send_request(input) elavult.  Alkalmazza inkább a send_request(req_params) hívást helyette"

#: fedora/client/baseclient.py:331
msgid ""
"Auth was requested but no way to perform auth was given.  Please set "
"username and password or session_id before calling this function with "
"auth=True"
msgstr "Auth kérés érkezett, de nem lehet végrehajtani az a megadott módon.  Kérjük, állítsa be felhasználói nevét és jelszavát, vagy session_id-jét mielőtt meghívná ezt a funkciót auth = True utasítással."

#: fedora/client/bodhi.py:195
msgid "You must specify a username"
msgstr "Meg kell adnod egy felhasználónevet"

#: fedora/client/bodhi.py:265
#, python-format
msgid "Reading from %s "
msgstr "Olvasás %s -ből "

#: fedora/client/fas2.py:269
#, python-format
msgid "FAS server unable to retrieve group %(group)s"
msgstr "A FAS kiszolgáló nem tudja visszaadni a %(group)s csoportot"

#: fedora/client/fas2.py:367
#, python-format
msgid "Size %(size)i disallowed.  Must be in %(valid_sizes)r"
msgstr "%(size)i méret nem engedélyezett. Érvényes méretek közt kell lennie: %(valid_sizes)r"

#: fedora/client/fas2.py:454
msgid "key must be one of \"id\", \"username\", or \"email\""
msgstr "a kulcsnak vagy „id” vagy „username” vagy „email” kell lennie"

#: fedora/client/fas2.py:461
#, python-format
msgid "%(field)s is not a valid field to filter"
msgstr "%(field)s érvénytelen mint szűrendő mező"

#: fedora/client/fas2.py:514
msgid ""
"people_by_id() is deprecated and will be removed in 0.4.  Please port your "
"code to use people_by_key(key='id', fields=['human_name', 'email', "
"'username', 'bugzilla_email']) instead"
msgstr "people_by_id() elavult, és a 0.4-es verzióban már nem lesz elérhető.  Kérem változtasson a kódon, hogy inkább a people_by_key(key='id', fields=['human_name',·'email', 'username', 'bugzilla_email']) hívást használja."

#: fedora/client/fas2.py:696
msgid "FAS server unable to retrieve group members"
msgstr "FAS kiszolgáló képtelen csoporttagokat lekérni"

#: fedora/client/fas2.py:718
msgid "FAS server unable to retrieve user information"
msgstr "FAS kiszolgáló képtelen a felhasználói adatokat lekérni"

#: fedora/client/fasproxy.py:67
msgid ""
"FasProxyClient() got an unexpected keyword argument 'session_as_cookie'"
msgstr "FasProxyClient() egy nem várt kulcsszó argumentumot kapott 'session_as_cookie'"

#: fedora/client/pkgdb.py:197
#, python-format
msgid ""
"We do not have enough information to create package %(pkg)s. Need version "
"owner."
msgstr "Nincs elég adat %(pkg)s csomag elkészítéséhez. Verzió tulajdonos szükséges."

#: fedora/client/pkgdb.py:208
#, python-format
msgid "PackageDB returned an error creating %(pkg)s: %(msg)s"
msgstr "%(pkg)s csomag készítése közben a PackageDB hibával tért vissza: %(msg)s"

#: fedora/client/pkgdb.py:231 fedora/client/pkgdb.py:287
#, python-format
msgid "Unable to save all information for %(pkg)s: %(msg)s"
msgstr "Nem sikerült %(pkg)s minden adatát elmenteni: %(msg)s"

#: fedora/client/pkgdb.py:323
#, python-format
msgid ""
"Collection abbreviation %(collection)s is unknown.  Use F, FC, EL, or OLPC"
msgstr "%(collection)s gyűjtemény rövidítés ismeretlen.  Használja F, FC, EL, \"\n\"vagy OLPC rövidítések valamelyikét."

#: fedora/client/pkgdb.py:350
msgid ""
"collection and collection_ver are deprecated names for collctn_name and "
"collctn_ver respectively.  Ignoring the values given in them."
msgstr "collection és a collection_ver az elavult nevei a collctn_name és collctn_ver utasításokat illetően. Az ezekben megadott értékek figyelmen kívülre kerülnek."

#: fedora/client/pkgdb.py:356
msgid ""
"collection has been renamed to collctn_name.\n"
"Please start using the new name.  collection will go away in 0.4.x."
msgstr "collection átnevezésre került: collctn_name.\nKérem kezdje el alkalmazni az új nevet.  collection el fog tűnni a 0.4.x -es verziótól kezdődően."

#: fedora/client/pkgdb.py:362
msgid ""
"collection_ver has been renamed to collctn_ver.\n"
"Please start using the new name.  collection_ver will go away in 0.4.x."
msgstr "collection_ver átnevezésre került: collctn_ver.\nKérem kezdje el alkalmazni az új nevet.  collection_ver el fog tűnni a 0.4.x -es verziótól kezdődően."

#: fedora/client/pkgdb.py:399
msgid ""
"collectn_list is a deprecated name for collctn_list.\n"
"Ignoring the value of collectn_list."
msgstr "collectn_list az elavult neve a collctn_list -nek.\nA collectn_list értéke figyelmen kívülre kerül."

#: fedora/client/pkgdb.py:404
msgid ""
"collectn_list has been renamed to collctn_list.\n"
"Please start using the new name.  collectn_list will go away in 0.4.x."
msgstr "collectn_list átnevezésre került: collctn_list.\nKérem kezdje el alkalmazni az új nevet.  collectn_list el fog tűnni a 0.4.x -es verziótól kezdődően."

#: fedora/client/pkgdb.py:478
msgid ""
"collectn is a deprecated name for collctn.\n"
"Ignoring the value of collectn."
msgstr "collectn az elavult neve a collctn-hez.\nA collectn értéke figyelmen kívülre kerül."

#: fedora/client/pkgdb.py:483
msgid ""
"collectn has been renamed to collctn.\n"
"Please start using the new name.  collectn will go away in 0.4.x."
msgstr "collectn átnevezésre került collctn parancsra.\nKérem használja az új nevet.  collectn el fog tűnni a 0.4.x. verziótól."

#: fedora/client/pkgdb.py:493
#, python-format
msgid "Collection shortname %(collctn)s is unknown."
msgstr "A gyűjtemény rövidítése %(collctn)s ismeretlen."

#: fedora/client/proxyclient.py:158
msgid "proxyclient.__init__:entered"
msgstr "proxyclient.__init__:belépve"

#: fedora/client/proxyclient.py:167
msgid ""
"Returning cookies from send_request() is deprecated and will be removed in "
"0.4.  Please port your code to use a session_id instead by calling the "
"ProxyClient constructor with session_as_cookie=False"
msgstr "A send_request() hívásból visszatérő sütik használata elavult, és 0.4-től már nem lesz.  Kérem változtasson, hogy inkább munkafolyamat azonosítót használjon a ProxyClient építő hívásakor session_as_cookie=False argumentummal."

#: fedora/client/proxyclient.py:174
msgid "proxyclient.__init__:exited"
msgstr "proxyclient.__init__:kilépve"

#: fedora/client/proxyclient.py:261
msgid "proxyclient.send_request: entered"
msgstr "proxyclient.send_request: belépve"

#: fedora/client/proxyclient.py:270
msgid ""
"Giving a cookie to send_request() to authenticate is deprecated and will be "
"removed in 0.4. Please port your code to use session_id instead."
msgstr "Süti megadása send_request() hívásnak hitelesítéshez elavult, és 0.4-től már nem lesz. Kérem változtasson: használjon inkább munkafolyamat azonosítót."

#: fedora/client/proxyclient.py:280
msgid "username and password must both be set in auth_params"
msgstr "használó nevet és jelszót is meg kell adni auth_params paraméterben"

#: fedora/client/proxyclient.py:283
msgid ""
"No known authentication methods specified: set \"cookie\" in auth_params or "
"set both username and password in auth_params"
msgstr "Nincs megadva ismert hitelesítő eljárás: használó nevet és jelszót auth_params paraméterben"

#: fedora/client/proxyclient.py:372
#, python-format
msgid "Creating request %(url)s"
msgstr "%(url)s kérelem megteremtése"

#: fedora/client/proxyclient.py:374
#, python-format
msgid "Headers: %(header)s"
msgstr "Fejlécek: %(header)s"

#: fedora/client/proxyclient.py:379
#, python-format
msgid "Data: %(data)s"
msgstr "Adatok: %(data)s"

#: fedora/client/proxyclient.py:396
msgid "Authentication failed logging in"
msgstr "Hitelesítésen bukott a bejelentkezés"

#: fedora/client/proxyclient.py:397
msgid ""
"Unable to log into server.  Invalid authentication tokens.  Send new "
"username and password"
msgstr "Nem lehet a szolgálóra bejelentkezni.  Érvénytelen hitelesítő adatok.  Küldjön új használó nevet és jelszót."

#: fedora/client/proxyclient.py:403
#, python-format
msgid "Attempt #%(try)s failed"
msgstr "Az #%(try)s próbálkozás sikertelen"

#: fedora/client/proxyclient.py:410
msgid "Unknown HTTP Server Response"
msgstr "Ismeretlen HTTP szolgáló válasz"

#: fedora/client/proxyclient.py:432
#, python-format
msgid "Error returned from json module while processing %(url)s: %(err)s"
msgstr "Hiba érkezett a json modulból az %(url)s feldolgozásakor: %(err)s"

#: fedora/client/proxyclient.py:448
msgid "proxyclient.send_request: exited"
msgstr "proxyclient.send_request: kilépve"

#: fedora/client/wiki.py:67
#, python-format
msgid "Login failed: %(data)s"
msgstr "Bejelentkezés sikertelen: %(data)s"

#: fedora/client/wiki.py:89
#, python-format
msgid "From %(then)s to %(now)s"
msgstr "%(then)s - %(now)s"

#: fedora/client/wiki.py:92
#, python-format
msgid "%d wiki changes in the past week"
msgstr "%d wiki változás a múlt héten"

#: fedora/client/wiki.py:94
msgid ""
"Warning: Number of changes reaches the API return limit.\n"
"You will not get the complete list of changes unless\n"
"you run this script using a 'bot' account."
msgstr "Figyelmeztetés: Számos változás éri el az API visszatérés korlátot.\nNem fogja megkapni a változások teljes listáját, hacsak nem\n„bot” számlára futtatja ezt az írást."

#: fedora/client/wiki.py:104
msgid ""
"\n"
"== Most active wiki users =="
msgstr "\n== Legtevékenyebb wiki használók =="

#: fedora/client/wiki.py:111
msgid ""
"\n"
"== Most edited pages =="
msgstr "\n== Legtöbbet szerkesztett oldalak =="

#: fedora/compat25/__init__.py:9
msgid ""
"fedora.pycompat25.defaultdict is deprecated, use "
"kitchen.pycompat25.collections.defaultdict instead"
msgstr "fedora.pycompat25.defaultdict elavult, alkalmazza a kitchen.pycompat25.collections.defaultdict helyette"

#: fedora/django/auth/models.py:50
msgid "Loading FAS groups..."
msgstr "Fedora csoportok betöltése…"

#: fedora/django/auth/models.py:56
msgid "Unable to load FAS groups. Did you set FAS_USERNAME and FAS_PASSWORD?"
msgstr "Nem lehet Fedora csoportokat betölteni. FAS_USERNAME és FAS_PASSWORD beállítva?"

#: fedora/django/auth/models.py:63
msgid ""
"FAS groups loaded. Don't forget to set FAS_USERNAME and FAS_PASSWORD to a "
"low-privilege account."
msgstr "FAS csoport betöltve. Ne felejtse el beállítani a FAS_USERNAME és FAS_PASSWORD változókat az alacsony prioritású felhasználói nevekhez."

#: fedora/tg/client.py:8
msgid ""
"fedora.tg.client has moved to fedora.client.  This location will disappear "
"in 0.4"
msgstr "fedora.tg.client elköltözött fedora.client helyre.  E hely el fog tűnni 0.4-ben"

#: fedora/tg/controllers.py:60
#, python-format
msgid "Welcome, %s"
msgstr "Üdvözlöm, %s"

#: fedora/tg/controllers.py:69
msgid ""
"The credentials you supplied were not correct or did not grant access to "
"this resource."
msgstr "A megadott igazolvány nem jó vagy nem jogosítja fel a hozzáférésre az erőforráshoz."

#: fedora/tg/controllers.py:72
msgid "You must provide your credentials before accessing this resource."
msgstr "Fel kell mutatnia az igazolványát, mielőtt hozzáfér az erőforráshoz."

#: fedora/tg/controllers.py:75
msgid "Please log in."
msgstr "Kérem jelentkezzen be."

#: fedora/tg/controllers.py:100
msgid "You have successfully logged out."
msgstr "Sikerült kijelentkezni."

#: fedora/tg/tg1utils.py:38
msgid ""
"fedora.tg.tg1utils is deprecated.  Switch to fedora.tg.utils instead.  This "
"file will disappear in 0.4"
msgstr "fedora.tg.tg1utils elavult.  Váltson fedora.tg.utils parancsra helyette.  Ez a fájl el fog tűnni a 0.4 verziótól kezdve."

#: fedora/tg/tg2utils.py:38
msgid ""
"fedora.tg.tg2utils is deprecated.  Switch to fedora.tg2.utils instead.  This"
" file will disappear in 0.4"
msgstr "fedora.tg.tg2utils elavult.  Váltson fedora.tg2.utils parancsra helyette.  Ez a fájl el fog tűnni a 0.4 verziótól kezdve."

#: fedora/tg/util.py:40
msgid ""
"fedora.tg.util is deprecated.  Switch to one of these instead:   TG1 apps: "
"fedora.tg.utils   TG2 apps: fedora.tg2.utils.  This file will disappear in "
"0.4"
msgstr "fedora.tg.util  elavult.  Váltson ezek közül az egyikre:   TG1 apps: fedora.tg.utils   TG2 apps: fedora.tg2.utils.  Ez a fájl el fog tűnni a 0.4 verziótól kezdve"

#: fedora/tg/utils.py:102
msgid "url() expects a dictionary for query parameters"
msgstr "url() python szótár típusú argumentumot vár a kérés paramétereiként"

#: fedora/tg/identity/jsonfasprovider1.py:223
#: fedora/tg/identity/jsonfasprovider2.py:409
#, python-format
msgid "Error logging in %(user)s: %(error)s"
msgstr "Hiba %(user)s bejelentkezésekor: %(error)s"

#: fedora/tg/identity/jsonfasprovider2.py:56
msgid ""
"Cannot enable ssl certificate auth via identity.ssl without setting "
"fas.usernamme and fas.password for authorization"
msgstr "Nem lehet engedélyezni ssl bizonyítványt identity.ssl-lel a fas.usernamme·és·fas.password megadása nélkül."

#: fedora/tg/identity/jsonfasprovider2.py:166
#, python-format
msgid "jsonfasprovider, ssl, returned errors from send_request: %s"
msgstr "jsonfasprovider, ssl, hibával tért vissza a send_requestből: %s"

#: fedora/tg/identity/jsonfasprovider2.py:181
#, python-format
msgid "jsonfasprovider returned errors from send_request: %s"
msgstr "jsonfasprovider·hibákkal tért vissza send_requestből:·%s"

#: fedora/tg/templates/genshi/login.html:10
#: fedora/tg2/templates/genshi/login.html:9
#: fedora/tg2/templates/mako/login.mak:3
msgid "Log In"
msgstr "Bejelentkezés"

#: fedora/tg/templates/genshi/login.html:14
msgid "User Name:"
msgstr "Használó:"

#: fedora/tg/templates/genshi/login.html:17
#: fedora/tg2/templates/genshi/login.html:31
#: fedora/tg2/templates/mako/login.mak:25
msgid "Password:"
msgstr "Jelszó:"

#: fedora/tg/templates/genshi/login.html:21
#: fedora/tg/templates/genshi/login.html:84
#: fedora/tg2/templates/genshi/login.html:33
#: fedora/tg2/templates/genshi/login.html:66
#: fedora/tg2/templates/mako/login.mak:27
#: fedora/tg2/templates/mako/login.mak:63
msgid "Login"
msgstr "Bejelentkezés"

#: fedora/tg/templates/genshi/login.html:28
#: fedora/tg2/templates/genshi/login.html:14
#: fedora/tg2/templates/mako/login.mak:9
msgid "CSRF attacks"
msgstr "CSRF támadások"

#: fedora/tg/templates/genshi/login.html:29
#: fedora/tg2/templates/genshi/login.html:15
#: fedora/tg2/templates/mako/login.mak:10
msgid ""
" are a means for a malicious website to make a request of another\n"
"        web server as the user who contacted the malicious web site.  The\n"
"        purpose of this page is to help protect your account and this server\n"
"        from attacks from such malicious web sites.  By clicking below, you are\n"
"        proving that you are a person rather than just the web browser\n"
"        forwarding your authentication cookies on behalf of a malicious\n"
"        website."
msgstr "rosszindulatú webhelyek eszköze arra, hogy kérést intézzen más\n        webszolgálókhoz a rosszindulatú webhellyel kapcsolatba lépő\n        használóként.  E lap célja, hogy segítsen megvédeni az ön\n        számláját és e szolgálót az ilyen rosszindulatú webhelyektől.\n        Alább kattintva ön bizonyítja, hogy inkább élő személy\n        mint csak egy rosszindulatú webhely nevében eljáró és az\n        ön hitelesítő sütijét továbbító webböngésző."

#: fedora/tg/templates/genshi/login.html:36
#: fedora/tg2/templates/genshi/login.html:23
#: fedora/tg2/templates/mako/login.mak:18
msgid "I am a human"
msgstr "Ember vagyok"

#: fedora/tg/templates/genshi/login.html:41
#: fedora/tg2/templates/genshi/login.html:37
#: fedora/tg2/templates/mako/login.mak:31
msgid "Forgot Password?"
msgstr "Elfelejtett jelszó?"

#: fedora/tg/templates/genshi/login.html:42
#: fedora/tg2/templates/genshi/login.html:38
#: fedora/tg2/templates/mako/login.mak:32
msgid "Sign Up"
msgstr "Beiratkozás"

#: fedora/tg/templates/genshi/login.html:60
#: fedora/tg2/templates/genshi/login.html:47
#: fedora/tg2/templates/mako/login.mak:40
msgid "Welcome"
msgstr "Üdvözöm"

#: fedora/tg/templates/genshi/login.html:82
#: fedora/tg2/templates/genshi/login.html:64
#: fedora/tg2/templates/mako/login.mak:61
msgid "You are not logged in"
msgstr "Ön nem jelentkezett be"

#: fedora/tg/templates/genshi/login.html:89
#: fedora/tg2/templates/genshi/login.html:70
#: fedora/tg2/templates/mako/login.mak:69
msgid "CSRF protected"
msgstr "CSRF védve"

#: fedora/tg/templates/genshi/login.html:91
#: fedora/tg2/templates/genshi/login.html:72
#: fedora/tg2/templates/mako/login.mak:72
msgid "Verify Login"
msgstr "Bejelentkezés ellenőrzése"

#: fedora/tg/templates/genshi/login.html:97
#: fedora/tg2/templates/genshi/login.html:78
#: fedora/tg2/templates/mako/login.mak:79
msgid "Logout"
msgstr "Kijelentkezés"

#: fedora/tg/visit/jsonfasvisit1.py:107 fedora/tg/visit/jsonfasvisit2.py:136
#, python-format
msgid "updating visit (%s)"
msgstr "látogatás frissítése (%s)"

#: fedora/tg2/templates/genshi/login.html:28
#: fedora/tg2/templates/mako/login.mak:22
msgid "Username:"
msgstr "Felhasználói név:"

#: fedora/wsgi/csrf.py:117
msgid "Creating CSRFProtectionMiddleware"
msgstr "CSRFProtectionMiddleware elkészítése"

#: fedora/wsgi/csrf.py:126
#, python-format
msgid "clean_environ(%s)"
msgstr "clean_environ(%s)"

#: fedora/wsgi/csrf.py:129
#, python-format
msgid "Deleting %(key)s from environ"
msgstr "A %(key)s törlése az environ-ból"

#: fedora/wsgi/csrf.py:142
#, python-format
msgid "CSRFProtectionMiddleware(%(r_path)s)"
msgstr "CSRFProtectionMiddleware(%(r_path)s)"

#: fedora/wsgi/csrf.py:149
msgid "User supplied CSRF token matches environ!"
msgstr "Felhasználó által használt CSRF tokennel egyezik az environ-nal!"

#: fedora/wsgi/csrf.py:152
msgid "Clearing identity"
msgstr "Identitás törlése"

#: fedora/wsgi/csrf.py:160
#, python-format
msgid ""
"Invalid CSRF token.  User supplied (%(u_token)s) does not match what's in "
"our environ (%(e_token)s)"
msgstr "Hibás CSRF token.  a felhasználó által megadott (%(u_token)s) nem egyezik a mi environ-unkban megadottal (%(e_token)s)"

#: fedora/wsgi/csrf.py:169
msgid "CSRF_AUTH_STATE; rewriting headers"
msgstr "CSRF_AUTH_STATE; fejlécek  újraírása"

#: fedora/wsgi/csrf.py:175
#, python-format
msgid "response.location = %(r_loc)s"
msgstr "response.location = %(r_loc)s"

#: fedora/wsgi/csrf.py:250
#, python-format
msgid "CSRFMetadataProvider.add_metadata(%(r_path)s)"
msgstr "CSRFMetadataProvider.add_metadata(%(r_path)s)"

#: fedora/wsgi/csrf.py:256
#, python-format
msgid "session_id = %(s_id)r"
msgstr "session_id = %(s_id)r"

#: fedora/wsgi/csrf.py:263
msgid "Identity updated with CSRF token"
msgstr "Azonosító frissítve CSRF tokennel"

#: fedora/wsgi/csrf.py:266
msgid "Setting CSRF_AUTH_STATE"
msgstr "CSRF_AUTH_STATE beállítása"

#: fedora/wsgi/csrf.py:276
msgid "Got HTTPFound(302) from repoze.who.application"
msgstr "a repoze.who.application forrásból HTTPFound(302) érkezett"

#: fedora/wsgi/csrf.py:289
#, python-format
msgid "Altered headers: %(headers)s"
msgstr "Megváltozott fejlécek: %(headers)s"

#: fedora/wsgi/csrf.py:292
#, python-format
msgid "Invalid session cookie %(s_id)r, not setting CSRF token!"
msgstr "Hibás folyamat cookie %(s_id)r, CSRF token nem kerül beállításra!"

#: fedora/wsgi/csrf.py:302
#, python-format
msgid "%(token)s in GET"
msgstr "%(token)s in GET"

#: fedora/wsgi/csrf.py:310
#, python-format
msgid "%(token)s in POST"
msgstr "%(token)s a POST-ban"

#: fedora/wsgi/faswho/faswhoplugin.py:208
msgid "in identify()"
msgstr "az identify()-ban"

#: fedora/wsgi/faswho/faswhoplugin.py:243
#, python-format
msgid "Request identify for cookie %(cookie)s"
msgstr "Azonosítási kérés a %(cookie)s cookie-hoz "

#: fedora/wsgi/faswho/faswhoplugin.py:263
msgid "In remember()"
msgstr "a remember()-ben"

#: fedora/wsgi/faswho/faswhoplugin.py:283
msgid "In forget()"
msgstr "a forget()-ben"

#: fedora/wsgi/faswho/faswhoplugin.py:293
#, python-format
msgid "Forgetting login data for cookie %(s_id)s"
msgstr "A cookie %(s_id)s bejelentkezési adatainak eldobása"

#: fedora/wsgi/faswho/faswhoplugin.py:307
msgid "In authenticate()"
msgstr "authenticate()-ban"

#: fedora/wsgi/faswho/faswhoplugin.py:339
msgid "Parameters for authenticating not found"
msgstr "Paraméterek az azonosításhoz nem találhatóak"

#: fedora/wsgi/faswho/faswhoplugin.py:345
#, python-format
msgid "Authentication failed: %s"
msgstr "Azonosítás sikertelen: %s"

#: fedora/wsgi/faswho/faswhoplugin.py:349
#, python-format
msgid "Unknown auth failure: %s"
msgstr "Ismeretlen azonsítási hiba: %s"

#: fedora/wsgi/faswho/faswhoplugin.py:358
msgid "user information from fas not in expected format!"
msgstr "felhasználói információ a FAS rendszerből nem a várt formában!"

#: fedora/wsgi/faswho/faswhoplugin.py:362
msgid "An unknown error happened when trying to log you in. Please try again."
msgstr "Ismeretlen hiba merült fel bejelentkezéskor. Kérem próbálja újra."

#: fedora/wsgi/faswho/faswhoplugin.py:367
msgid "In add_metadata"
msgstr "az add_metadata-ban"

#: fedora/wsgi/faswho/faswhoplugin.py:371
msgid "Error exists in session, no need to set metadata"
msgstr "Hiba a munkafolyamatban, nincs szükség a metaadatok beállítására"

#: fedora/wsgi/test/controllers/root.py:31
msgid "Wrong credentials"
msgstr "Hibás ajánlás"

#: fedora/wsgi/test/controllers/root.py:46
#, python-format
msgid "Welcome back, %s!"
msgstr "Üdvözlünk újra, %s!"

#: fedora/wsgi/test/controllers/root.py:56
msgid "We hope to see you soon!"
msgstr "Reméljük még találkozunk nem sokára!"
